name: Build and push Docker image

on:
  push:
    branches:
      - '**'
    tags:
      - "**"
    paths-ignore:
      - '**/tasks/**'
      - '**/*.md'
      - '*.md'

jobs:
  build:
    uses: ./.github/workflows/docker_build.yml
    with:
      BUILD_CONTEXT: './src/backend/'
    secrets:
      DOCKER_USERNAME: ${{ github.actor  }}
      DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
