name: Build and push Docker image

on:
  push:
    branches:
      - '**'
    tags:
      - "**"

jobs:
  build:
    uses: ./.github/workflows/docker_build.yml
    with:
      DOCKERFILE: './src/backend/Dockerfile'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
