name: Build and push Docker image for Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: ./docker_release.yaml
    with:
      IMAGE_NAME: ${{ vars.DOKKEN_REPO_NAME }}
      DOCKERFILE: './src/backend/Dockerfile'
    secrets:
      DOKKEN_CLIENT_ID: ${{ secrets.DOKKEN_CLIENT_ID }}
      DOKKEN_CLIENT_SECRET: ${{ secrets.DOKKEN_CLIENT_SECRET }}
